title: Rick's ranting about getting email responses for RTC validation
theme: minima
author: RickABuss
email: rickbuss@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my awesome blog about getting people to reply to the RTC validation notices I send out.  
  I will point them to my blog so thay can read how important this is
  
# social links
twitter_username: RickABuss # DO NOT include the @ character, or else the build will fail!
github_username:  rickabuss # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
